kumuluzee:
  name: ms.friends
  env:
    name: dev
  version: 1.0.0
  server:
      base-url:
      http:
        port:
  datasources:
    - jndi-name: jdbc/RsobookDS
      connection-url: jdbc:postgresql://localhost:55432/rsobook-user_friends
      username: postgres
      password: root
      max-pool-size: 10
  config:
      etcd:
        hosts: http://localhost:52379
  discovery:
    etcd:
      hosts: http://localhost:52379
    ttl: 20
    ping-interval: 15
  cors-filter:
    servlet:
      allow-origin: "*"
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: false
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/RsobookDS
      disk-space-health-check:
        threshold: 100000000
  metrics:
    generic-registry-name: default
    jvm:
      enabled: true
      registry-name: jvm
    servlet:
      enabled: true
      mapping: /metrics
    logs:
      enabled: false
      period-s: 30
      level: INFO
    web-instrumentation:
      - name: friends-endpoint
        url-pattern: /api/v1/Friends/*

properties:
  user-api-host: http://localhost:55001