apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-friends
spec:
  replicas: 1
  selector:
        matchLabels:
          app: ms-friends
  template:
    metadata:
      labels:
        app: ms-friends
    spec:
      containers:
        - image: rsobook/ms-friends:2.0.0
          name: ms-friends
          env:
            - name: PORT
              value: '80'
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: PROPERTIES_USERAPIHOST
              value: http://ms-user
            - name: PROPERTIES_USERAPIHOSTDISCOVERY
              value: 'false'
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ms-database:5432/rsobook-user_friends
          ports:
          - containerPort: 80
            protocol: TCP